# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3qvSJuWNyKNqWMJYd-HRUMEc-STNdSs
"""

import os
from dotenv import load_dotenv
from google import genai

load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=api_key)

#conversation memory and a system prompt
system_prompt = "You are a friendly and encouraging coding tutor. Keep answers simple and clear for a beginner."

conversation_history = []

print("Chatbot ready! type 'quit' to exit.")

while True:
    user_input = input("You: ")
    if user_input.lower() == "quit":
        break

    conversation_history.append({"role": "user", "parts": [{"text": user_input}]})

    # Send the full history (with system prompt) to the model
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents = conversation_history,
        config = {"system_instruction": system_prompt}
    )

    bot_reply = response.text
    print(f"Bot: {bot_reply}\n")

    #Add the bot's reply to the conversation history
    conversation_history.append({"role": "model", "parts": [{"text": bot_reply}]})