# -*- coding: utf-8 -*-
"""rag_chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ds9R_wrzrImpwMlQv79gyPXtA-RH-Nb
"""

import os
from dotenv import load_dotenv
from google import genai
import numpy as np

load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=api_key)

def load_and_chunk(filepath, chunk_size = 500):
    with open(filepath, 'r', encoding='utf-8') as file:
        text = file.read()

    # Split the text into chunks of specified size
    chunks = []
    for i in range(0, len(text), chunk_size):
        chunk = text[i:i + chunk_size]
        chunks.append(chunk)
    return chunks

def get_embedding(text):
    result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=text
    )
    return result.embeddings[0].values

def cosine_similarity(vec1, vec2):
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)
    return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

def find_best_chunk(query, chunks, chunk_embeddings, top_n=2):
    query_embedding = get_embedding(query)
    similarities = []
    for i, chunk_embedding in enumerate(chunk_embeddings):
        score = cosine_similarity(query_embedding, chunk_embedding)
        similarities.append((score, i))

    similarities.sort(reverse=True)
    top_chunks = []
    for score, index in similarities[:top_n]:
        top_chunks.append((chunks[index]))

    return top_chunks

def answer_question(question, chunks, chunk_embeddings):
    best_chunks = find_best_chunk(question, chunks, chunk_embeddings)
    context = "\n\n".join(best_chunks)

    prompt = f"""Answer the question using ONLY the context provided below.
    If the answer isn't in the context, say "I don't have that information in my notes."

    Context:
    {context}
    Question: {question}

    Answer:"""

    # Step 3: Generate the answer
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text

chunks = load_and_chunk('notes.txt')
print(f"split into {len(chunks)} chunks.\n")
chunk_embeddings = [get_embedding(chunk) for chunk in chunks]
print(f"created {len(chunk_embeddings)} embeddings.\n")

# --- Test retrieval ---
print("Ask me anything about your notes. Type 'quit' to exit.\n")

while True:
    question = input("You: ")
    if question.lower() == "quit":
        print("Goodbye!")
        break

    answer = answer_question(question, chunks, chunk_embeddings)
    print(f"\nBot: {answer}\n")